config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :blog_posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  root 'blog_posts#index'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog_post
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blog_posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :birthday])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :birthday])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :blog_entry, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      if @comment.save
        format.html{redirect_to blog_post_path(@comment.blog_post_id), notice: 'Comment was successfully created.'}
      else
        format.html{redirect_to blog_post_path}
      end
    end
end
def edit
   @blog_post = BlogPost.find(params[:blog_post_id])
   @comment = Comment.find(params[:id])
 end
 def update
   @comment = Comment.find(params[:id])
   respond_to do |format|
     if @comment.update(comment_params)
       format.html{redirect_to blog_post_path( @comment.blog_post_id), notice: 'Comment was successfully created.'}
     else
       format.html { redirect_to blog_post_path}
     end
   end
 end
 def destroy
   @comment = Comment.find(params[:id])
   @comment.destroy
   respond_to do |format|
     format.html { redirect_to blog_post_path(@comment.blog_post), notice: 'Comment was successfully destroyed.' }
   end
 end
private

def comment_params
  params.require(:comment).permit(:author, :comment_entry, :blog_post_id, :user_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: "form-control", placeholder: "Post Title" %>
  </div>
  
  <div class="form-group">
    <%= f.text_area :blog_entry, class: "form-control", :rows => 20, placeholder: "Speak Your Mind!" %>
  </div>
  <div class="form-group cant-see-me">
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">


<h1>Blog Posts</h1>
  <div class="row">
    <% @blog_posts.each do |blog_post| %>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to blog_post.title, blog_post %>
          </div>
          <div class="panel-body">
             by <%= blog_post.user.email %>
             <p><span class="posted-at">posted at: <%= blog_post.created_at.strftime('%m/%d/%y at %I:%M%p')%></span>
             </p>
            <p><%= blog_post.blog_entry[0..250] %>...[<%= link_to "Read More", blog_post %>]</p>
          </div>
          <div class="panel-footer">
            <%= link_to 'Edit', edit_blog_post_path(blog_post), class: "btn btn-warning" %>
            <%= link_to 'Destroy', blog_post, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
      <% end %>
  </div>
<br>

<%= link_to 'New Blog post', new_blog_post_path %>
</div>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">


<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @blog_post.title %>
  </div>
  <div class="panel-body">
    <p> by <strong><%= @blog_post.user.email %></strong> at <%= @blog_post.created_at.strftime('%m/%d/y %H:%M:%S') %></p>
    <p><%= @blog_post.blog_entry %></p>
  </div>
  <div class="panel-footer">
    <%= link_to 'Edit', edit_blog_post_path(@blog_post), class: "btn btn-warning" %>
    <%= link_to 'Destroy', @blog_post, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
</div>
  </div>

<div class="panel panel-success">
  <div class="panel-heading">
    Write a Comment
  </div>
  <div class="panel-body">
    <%= render 'comments/form' %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Comments</h4>
  </div>
  <% @blog_post.comments.each do |comment| %>
    <div class="panel-body">
      <p><strong><%= comment.user.email %></strong> said: </p>
      <p><%= comment.comment_entry %></p>
      <%= link_to "Edit Comment", edit_blog_post_comment_path(@blog_post, comment) %> |
      <%= link_to 'Destroy', [comment.blog_post, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= comment.created_at.strftime('%m/%d/%y at %I:%M%p') %>
    </div>
    <% end %>
</div>
<%= link_to 'Back', blog_posts_path %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@blog_post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "errors") %> prohibited this comment from being saved: </h2>
    <ul>
          <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      
      <div class="form-group">
        <%= f.text_area :comment_entry, class: "form-control", :rows => 10, placeholder: "What Do You Think?" %>
      </div>
      <div class="cant-see-me">
    <%= f.number_field :blog_post_id, value: @blog_post.id %>
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
      <div class="actions">
        <%= f.submit %>
      </div>

    <% end %>

app/views/comments/edit.html.erb
<%= form_for([@blog_post, @comment], url: blog_post_comment_path) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :comment_entry, class:"sr-only" %><br>
    <%= f.text_area :comment_entry, class: "form-control", placeholder: "Comment", rows: 5 %>
  </div>
  <div class="form-group">
    <%= f.label :author, class:"sr-only" %><br>
    <%= f.text_field :author, class: "form-control", placeholder: "author" %>
  </div>
  <div class="field cant-see-me">
    <%= f.number_field :blog_post_id, value: @blog_post.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>Tech Talent Blog</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"%>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="pull-right">
      <% if user_signed_in? %>
       <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
      <% end %>
    </div>
  
</div>
<%= yield %>
</body>
</html>